// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_colour_num_variable_hex
Rcpp::StringVector rcpp_colour_num_variable_hex(Rcpp::NumericVector x, std::string palette, std::string na_colour);
RcppExport SEXP _RcppViridis_rcpp_colour_num_variable_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_variable_hex(x, palette, na_colour));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_variable_hex
Rcpp::StringVector rcpp_colour_str_variable_hex(Rcpp::StringVector x, std::string palette, std::string na_colour);
RcppExport SEXP _RcppViridis_rcpp_colour_str_variable_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_variable_hex(x, palette, na_colour));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_dte_variable_hex
Rcpp::StringVector rcpp_colour_dte_variable_hex(Rcpp::DateVector x, std::string palette, std::string na_colour);
RcppExport SEXP _RcppViridis_rcpp_colour_dte_variable_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DateVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_dte_variable_hex(x, palette, na_colour));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_is_hex_colour
Rcpp::LogicalVector rcpp_is_hex_colour(Rcpp::StringVector hex);
RcppExport SEXP _RcppViridis_rcpp_is_hex_colour(SEXP hexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type hex(hexSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_is_hex_colour(hex));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppViridis_rcpp_colour_num_variable_hex", (DL_FUNC) &_RcppViridis_rcpp_colour_num_variable_hex, 3},
    {"_RcppViridis_rcpp_colour_str_variable_hex", (DL_FUNC) &_RcppViridis_rcpp_colour_str_variable_hex, 3},
    {"_RcppViridis_rcpp_colour_dte_variable_hex", (DL_FUNC) &_RcppViridis_rcpp_colour_dte_variable_hex, 3},
    {"_RcppViridis_rcpp_is_hex_colour", (DL_FUNC) &_RcppViridis_rcpp_is_hex_colour, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppViridis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
