// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_colour_num_value_string_palette_hex
Rcpp::StringVector rcpp_colour_num_value_string_palette_hex(Rcpp::NumericVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_string_palette_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_string_palette_hex(x, palette, na_colour, alpha, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_string_palette_summary_hex
Rcpp::List rcpp_colour_num_value_string_palette_summary_hex(Rcpp::NumericVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha, int n_summaries, bool format, std::string format_type, int digits);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_string_palette_summary_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP, SEXP n_summariesSEXP, SEXP formatSEXP, SEXP format_typeSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_summaries(n_summariesSEXP);
    Rcpp::traits::input_parameter< bool >::type format(formatSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_type(format_typeSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_string_palette_summary_hex(x, palette, na_colour, alpha, include_alpha, n_summaries, format, format_type, digits));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_rgb_palette_hex
Rcpp::StringVector rcpp_colour_num_value_rgb_palette_hex(Rcpp::NumericVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_rgb_palette_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_rgb_palette_hex(x, palette, na_colour, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_rgb_palette_summary_hex
Rcpp::List rcpp_colour_num_value_rgb_palette_summary_hex(Rcpp::NumericVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha, int n_summaries, bool format, std::string format_type, int digits);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_rgb_palette_summary_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP, SEXP n_summariesSEXP, SEXP formatSEXP, SEXP format_typeSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_summaries(n_summariesSEXP);
    Rcpp::traits::input_parameter< bool >::type format(formatSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_type(format_typeSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_rgb_palette_summary_hex(x, palette, na_colour, include_alpha, n_summaries, format, format_type, digits));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_string_palette_hex
Rcpp::StringVector rcpp_colour_str_value_string_palette_hex(Rcpp::StringVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_string_palette_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_string_palette_hex(x, palette, na_colour, alpha, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_string_palette_summary_hex
Rcpp::List rcpp_colour_str_value_string_palette_summary_hex(Rcpp::StringVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha, bool summary);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_string_palette_summary_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_string_palette_summary_hex(x, palette, na_colour, alpha, include_alpha, summary));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_rgb_palette_hex
Rcpp::StringVector rcpp_colour_str_value_rgb_palette_hex(Rcpp::StringVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_rgb_palette_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_rgb_palette_hex(x, palette, na_colour, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_rgb_palette_summary_hex
Rcpp::List rcpp_colour_str_value_rgb_palette_summary_hex(Rcpp::StringVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha, bool summary);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_rgb_palette_summary_hex(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_rgb_palette_summary_hex(x, palette, na_colour, include_alpha, summary));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_string_palette_rgb
Rcpp::NumericMatrix rcpp_colour_num_value_string_palette_rgb(Rcpp::NumericVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_string_palette_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_string_palette_rgb(x, palette, na_colour, alpha, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_string_palette_summary_rgb
Rcpp::List rcpp_colour_num_value_string_palette_summary_rgb(Rcpp::NumericVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha, int n_summaries, bool format, std::string format_type, int digits);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_string_palette_summary_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP, SEXP n_summariesSEXP, SEXP formatSEXP, SEXP format_typeSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_summaries(n_summariesSEXP);
    Rcpp::traits::input_parameter< bool >::type format(formatSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_type(format_typeSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_string_palette_summary_rgb(x, palette, na_colour, alpha, include_alpha, n_summaries, format, format_type, digits));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_rgb_palette_rgb
Rcpp::NumericMatrix rcpp_colour_num_value_rgb_palette_rgb(Rcpp::NumericVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_rgb_palette_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_rgb_palette_rgb(x, palette, na_colour, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_num_value_rgb_palette_summary_rgb
Rcpp::List rcpp_colour_num_value_rgb_palette_summary_rgb(Rcpp::NumericVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha, int n_summaries, bool format, std::string format_type, int digits);
RcppExport SEXP _colourvalues_rcpp_colour_num_value_rgb_palette_summary_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP, SEXP n_summariesSEXP, SEXP formatSEXP, SEXP format_typeSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_summaries(n_summariesSEXP);
    Rcpp::traits::input_parameter< bool >::type format(formatSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_type(format_typeSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_num_value_rgb_palette_summary_rgb(x, palette, na_colour, include_alpha, n_summaries, format, format_type, digits));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_string_palette_rgb
Rcpp::NumericMatrix rcpp_colour_str_value_string_palette_rgb(Rcpp::StringVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_string_palette_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_string_palette_rgb(x, palette, na_colour, alpha, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_string_palette_summary_rgb
Rcpp::List rcpp_colour_str_value_string_palette_summary_rgb(Rcpp::StringVector x, std::string palette, std::string na_colour, Rcpp::NumericVector alpha, bool include_alpha, bool summary);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_string_palette_summary_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP alphaSEXP, SEXP include_alphaSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_string_palette_summary_rgb(x, palette, na_colour, alpha, include_alpha, summary));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_rgb_palette_rgb
Rcpp::NumericMatrix rcpp_colour_str_value_rgb_palette_rgb(Rcpp::StringVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_rgb_palette_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_rgb_palette_rgb(x, palette, na_colour, include_alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_colour_str_value_rgb_palette_summary_rgb
Rcpp::List rcpp_colour_str_value_rgb_palette_summary_rgb(Rcpp::StringVector x, Rcpp::NumericMatrix palette, std::string na_colour, bool include_alpha, bool summary);
RcppExport SEXP _colourvalues_rcpp_colour_str_value_rgb_palette_summary_rgb(SEXP xSEXP, SEXP paletteSEXP, SEXP na_colourSEXP, SEXP include_alphaSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type palette(paletteSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_colour(na_colourSEXP);
    Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_colour_str_value_rgb_palette_summary_rgb(x, palette, na_colour, include_alpha, summary));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_convert_hex_to_rgb
Rcpp::IntegerMatrix rcpp_convert_hex_to_rgb(Rcpp::StringVector hex_strings);
RcppExport SEXP _colourvalues_rcpp_convert_hex_to_rgb(SEXP hex_stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type hex_strings(hex_stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_convert_hex_to_rgb(hex_strings));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_convert_rgb_mat_to_hex
Rcpp::StringVector rcpp_convert_rgb_mat_to_hex(Rcpp::IntegerMatrix rgb);
RcppExport SEXP _colourvalues_rcpp_convert_rgb_mat_to_hex(SEXP rgbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rgb(rgbSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_convert_rgb_mat_to_hex(rgb));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_convert_rgb_vec_to_hex
Rcpp::StringVector rcpp_convert_rgb_vec_to_hex(Rcpp::IntegerVector rgb);
RcppExport SEXP _colourvalues_rcpp_convert_rgb_vec_to_hex(SEXP rgbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type rgb(rgbSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_convert_rgb_vec_to_hex(rgb));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_viridis
Rcpp::DataFrame rcpp_viridis();
RcppExport SEXP _colourvalues_rcpp_viridis() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_viridis());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_inferno
Rcpp::DataFrame rcpp_inferno();
RcppExport SEXP _colourvalues_rcpp_inferno() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_inferno());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_magma
Rcpp::DataFrame rcpp_magma();
RcppExport SEXP _colourvalues_rcpp_magma() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_magma());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_plasma
Rcpp::DataFrame rcpp_plasma();
RcppExport SEXP _colourvalues_rcpp_plasma() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_plasma());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cividis
Rcpp::DataFrame rcpp_cividis();
RcppExport SEXP _colourvalues_rcpp_cividis() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_cividis());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_colourvalues_rcpp_colour_num_value_string_palette_hex", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_string_palette_hex, 5},
    {"_colourvalues_rcpp_colour_num_value_string_palette_summary_hex", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_string_palette_summary_hex, 9},
    {"_colourvalues_rcpp_colour_num_value_rgb_palette_hex", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_rgb_palette_hex, 4},
    {"_colourvalues_rcpp_colour_num_value_rgb_palette_summary_hex", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_rgb_palette_summary_hex, 8},
    {"_colourvalues_rcpp_colour_str_value_string_palette_hex", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_string_palette_hex, 5},
    {"_colourvalues_rcpp_colour_str_value_string_palette_summary_hex", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_string_palette_summary_hex, 6},
    {"_colourvalues_rcpp_colour_str_value_rgb_palette_hex", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_rgb_palette_hex, 4},
    {"_colourvalues_rcpp_colour_str_value_rgb_palette_summary_hex", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_rgb_palette_summary_hex, 5},
    {"_colourvalues_rcpp_colour_num_value_string_palette_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_string_palette_rgb, 5},
    {"_colourvalues_rcpp_colour_num_value_string_palette_summary_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_string_palette_summary_rgb, 9},
    {"_colourvalues_rcpp_colour_num_value_rgb_palette_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_rgb_palette_rgb, 4},
    {"_colourvalues_rcpp_colour_num_value_rgb_palette_summary_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_num_value_rgb_palette_summary_rgb, 8},
    {"_colourvalues_rcpp_colour_str_value_string_palette_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_string_palette_rgb, 5},
    {"_colourvalues_rcpp_colour_str_value_string_palette_summary_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_string_palette_summary_rgb, 6},
    {"_colourvalues_rcpp_colour_str_value_rgb_palette_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_rgb_palette_rgb, 4},
    {"_colourvalues_rcpp_colour_str_value_rgb_palette_summary_rgb", (DL_FUNC) &_colourvalues_rcpp_colour_str_value_rgb_palette_summary_rgb, 5},
    {"_colourvalues_rcpp_convert_hex_to_rgb", (DL_FUNC) &_colourvalues_rcpp_convert_hex_to_rgb, 1},
    {"_colourvalues_rcpp_convert_rgb_mat_to_hex", (DL_FUNC) &_colourvalues_rcpp_convert_rgb_mat_to_hex, 1},
    {"_colourvalues_rcpp_convert_rgb_vec_to_hex", (DL_FUNC) &_colourvalues_rcpp_convert_rgb_vec_to_hex, 1},
    {"_colourvalues_rcpp_viridis", (DL_FUNC) &_colourvalues_rcpp_viridis, 0},
    {"_colourvalues_rcpp_inferno", (DL_FUNC) &_colourvalues_rcpp_inferno, 0},
    {"_colourvalues_rcpp_magma", (DL_FUNC) &_colourvalues_rcpp_magma, 0},
    {"_colourvalues_rcpp_plasma", (DL_FUNC) &_colourvalues_rcpp_plasma, 0},
    {"_colourvalues_rcpp_cividis", (DL_FUNC) &_colourvalues_rcpp_cividis, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_colourvalues(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
