# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_colour_values_hex <- function(x, palette, alpha, na_colour = "#808080", include_alpha = TRUE, format = FALSE, digits = 2L, summary = FALSE, n_summaries = 0L) {
    .Call(`_colourvalues_rcpp_colour_values_hex`, x, palette, alpha, na_colour, include_alpha, format, digits, summary, n_summaries)
}

rcpp_colour_values_rgb <- function(x, palette, alpha, na_colour = "#808080", include_alpha = TRUE, format = FALSE, digits = 2L, summary = FALSE, n_summaries = 0L) {
    .Call(`_colourvalues_rcpp_colour_values_rgb`, x, palette, alpha, na_colour, include_alpha, format, digits, summary, n_summaries)
}

rcpp_colour_values_rgb_interleaved <- function(x, palette, alpha, repeats, total_colours, na_colour = "#808080", include_alpha = TRUE, format = FALSE, digits = 2L, summary = FALSE, n_summaries = 0L) {
    .Call(`_colourvalues_rcpp_colour_values_rgb_interleaved`, x, palette, alpha, repeats, total_colours, na_colour, include_alpha, format, digits, summary, n_summaries)
}

rcpp_convert_hex_to_rgb <- function(hex_strings) {
    .Call(`_colourvalues_rcpp_convert_hex_to_rgb`, hex_strings)
}

rcpp_convert_rgb_mat_to_hex <- function(rgb) {
    .Call(`_colourvalues_rcpp_convert_rgb_mat_to_hex`, rgb)
}

rcpp_convert_rgb_vec_to_hex <- function(rgb) {
    .Call(`_colourvalues_rcpp_convert_rgb_vec_to_hex`, rgb)
}

rcpp_validate_alpha <- function(alpha, alpha_type) {
    .Call(`_colourvalues_rcpp_validate_alpha`, alpha, alpha_type)
}

rcpp_get_format_type <- function(palette_type) {
    .Call(`_colourvalues_rcpp_get_format_type`, palette_type)
}

rcpp_get_r_class <- function(obj) {
    .Call(`_colourvalues_rcpp_get_r_class`, obj)
}

rcpp_vector_type <- function(new_type, existing_type) {
    .Call(`_colourvalues_rcpp_vector_type`, new_type, existing_type)
}

rcpp_list_size <- function(lst, total_size, existing_type, format_type) {
    .Call(`_colourvalues_rcpp_list_size`, lst, total_size, existing_type, format_type)
}

rcpp_refil_list <- function(lst_sizes, colours, vector_position) {
    .Call(`_colourvalues_rcpp_refil_list`, lst_sizes, colours, vector_position)
}

rcpp_validate_rgb_range <- function(x) {
    .Call(`_colourvalues_rcpp_validate_rgb_range`, x)
}

rcpp_validate_rgb_spline <- function(x) {
    .Call(`_colourvalues_rcpp_validate_rgb_spline`, x)
}

rcpp_get_palette <- function(palette) {
    .Call(`_colourvalues_rcpp_get_palette`, palette)
}

rcpp_viridis <- function() {
    .Call(`_colourvalues_rcpp_viridis`)
}

rcpp_inferno <- function() {
    .Call(`_colourvalues_rcpp_inferno`)
}

rcpp_magma <- function() {
    .Call(`_colourvalues_rcpp_magma`)
}

rcpp_plasma <- function() {
    .Call(`_colourvalues_rcpp_plasma`)
}

rcpp_cividis <- function() {
    .Call(`_colourvalues_rcpp_cividis`)
}

rcpp_terrain <- function() {
    .Call(`_colourvalues_rcpp_terrain`)
}

rcpp_topo <- function() {
    .Call(`_colourvalues_rcpp_topo`)
}

rcpp_heat <- function() {
    .Call(`_colourvalues_rcpp_heat`)
}

rcpp_ylorrd <- function() {
    .Call(`_colourvalues_rcpp_ylorrd`)
}

rcpp_ylorbr <- function() {
    .Call(`_colourvalues_rcpp_ylorbr`)
}

rcpp_ylgnbu <- function() {
    .Call(`_colourvalues_rcpp_ylgnbu`)
}

rcpp_ylgn <- function() {
    .Call(`_colourvalues_rcpp_ylgn`)
}

rcpp_reds <- function() {
    .Call(`_colourvalues_rcpp_reds`)
}

rcpp_rdpu <- function() {
    .Call(`_colourvalues_rcpp_rdpu`)
}

rcpp_purples <- function() {
    .Call(`_colourvalues_rcpp_purples`)
}

rcpp_purd <- function() {
    .Call(`_colourvalues_rcpp_purd`)
}

rcpp_pubugn <- function() {
    .Call(`_colourvalues_rcpp_pubugn`)
}

rcpp_pubu <- function() {
    .Call(`_colourvalues_rcpp_pubu`)
}

rcpp_orrd <- function() {
    .Call(`_colourvalues_rcpp_orrd`)
}

rcpp_oranges <- function() {
    .Call(`_colourvalues_rcpp_oranges`)
}

rcpp_greys <- function() {
    .Call(`_colourvalues_rcpp_greys`)
}

rcpp_greens <- function() {
    .Call(`_colourvalues_rcpp_greens`)
}

rcpp_gnbu <- function() {
    .Call(`_colourvalues_rcpp_gnbu`)
}

rcpp_bupu <- function() {
    .Call(`_colourvalues_rcpp_bupu`)
}

rcpp_bugn <- function() {
    .Call(`_colourvalues_rcpp_bugn`)
}

rcpp_blues <- function() {
    .Call(`_colourvalues_rcpp_blues`)
}

rcpp_spectral <- function() {
    .Call(`_colourvalues_rcpp_spectral`)
}

rcpp_rdylgn <- function() {
    .Call(`_colourvalues_rcpp_rdylgn`)
}

rcpp_rdylbu <- function() {
    .Call(`_colourvalues_rcpp_rdylbu`)
}

rcpp_rdgy <- function() {
    .Call(`_colourvalues_rcpp_rdgy`)
}

rcpp_rdbu <- function() {
    .Call(`_colourvalues_rcpp_rdbu`)
}

rcpp_puor <- function() {
    .Call(`_colourvalues_rcpp_puor`)
}

rcpp_prgn <- function() {
    .Call(`_colourvalues_rcpp_prgn`)
}

rcpp_piyg <- function() {
    .Call(`_colourvalues_rcpp_piyg`)
}

rcpp_brbg <- function() {
    .Call(`_colourvalues_rcpp_brbg`)
}

rcpp_cm <- function() {
    .Call(`_colourvalues_rcpp_cm`)
}

rcpp_rainbow <- function() {
    .Call(`_colourvalues_rcpp_rainbow`)
}

rcpp_ygobb <- function() {
    .Call(`_colourvalues_rcpp_ygobb`)
}

rcpp_matlab_like2 <- function() {
    .Call(`_colourvalues_rcpp_matlab_like2`)
}

rcpp_matlab_like <- function() {
    .Call(`_colourvalues_rcpp_matlab_like`)
}

rcpp_magenta2green <- function() {
    .Call(`_colourvalues_rcpp_magenta2green`)
}

rcpp_cyan2yellow <- function() {
    .Call(`_colourvalues_rcpp_cyan2yellow`)
}

rcpp_blue2yellow <- function() {
    .Call(`_colourvalues_rcpp_blue2yellow`)
}

rcpp_green2red <- function() {
    .Call(`_colourvalues_rcpp_green2red`)
}

rcpp_blue2green <- function() {
    .Call(`_colourvalues_rcpp_blue2green`)
}

rcpp_blue2red <- function() {
    .Call(`_colourvalues_rcpp_blue2red`)
}

rcpp_diverge_hcl <- function() {
    .Call(`_colourvalues_rcpp_diverge_hcl`)
}

rcpp_diverge_hsv <- function() {
    .Call(`_colourvalues_rcpp_diverge_hsv`)
}

rcpp_terrain_hcl <- function() {
    .Call(`_colourvalues_rcpp_terrain_hcl`)
}

rcpp_heat_hcl <- function() {
    .Call(`_colourvalues_rcpp_heat_hcl`)
}

rcpp_sequential_hcl <- function() {
    .Call(`_colourvalues_rcpp_sequential_hcl`)
}

rcpp_rainbow_hcl <- function() {
    .Call(`_colourvalues_rcpp_rainbow_hcl`)
}

rcpp_scale <- function(x) {
    .Call(`_colourvalues_rcpp_scale`, x)
}

