# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_colour_num_variable_hex <- function(x, palette) {
    .Call(`_RcppViridis_rcpp_colour_num_variable_hex`, x, palette)
}

rcpp_colour_str_variable_hex <- function(x, palette) {
    .Call(`_RcppViridis_rcpp_colour_str_variable_hex`, x, palette)
}

